### ISSUE TITLE
Named import in typescript

### ISSUE THREAD

**Issue by martinsura** [mistlog/svelte-draft#6]
Hi,

First - nice idea. I have question

Its possible use svelte-draft and typescript with no default exports?

For example:

```
App.tsx

import {Component} from "./Component";

export default function App(){
   <Component />
   ...
}

Component.tsx

export const Component = () => {
<h1>Hello world</h1>
}
```

Now i got error:

```
Module build failed (from ./node_modules/svelte-draft-loader/src/index.js):
TypeError: Cannot read property 'get' of undefined
    at FindComponentBody (C:\Develop\Projects\Temp\sveltetest\node_modules\svelte-draft\src\transcriber\svelte-transcriber.js:82:28)
    at SvelteTranscriber.TranscribeToSections (C:\Develop\Projects\Temp\sveltetest\node_modules\svelte-draft\src\transcriber\svelte-transcriber.js:57:22)
    at Transcribe (C:\Develop\Projects\Temp\sveltetest\node_modules\svelte-draft\cli\literator.js:148:78)
    at C:\Develop\Projects\Temp\sveltetest\node_modules\svelte-draft\cli\literator.js:122:86
    at Generator.next (<anonymous>)
    at fulfilled (C:\Develop\Projects\Temp\sveltetest\node_modules\svelte-draft\cli\literator.js:5:58)
 @ ./src/app.tsx 22:0-40 31:23-32
```

my package.json
```
{
  "name": "sveltetest",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "devDependencies": {
    "css-loader": "^3.4.2",
    "fork-ts-checker-webpack-plugin": "^4.1.1",
    "mini-css-extract-plugin": "^0.9.0",
    "node-sass": "^4.13.1",
    "prettier": "^2.0.1",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3",
    "svelte-draft-loader": "^1.0.1",
    "svelte-loader": "^2.13.6",
    "svelte-types": "0.0.6",
    "ts-loader": "^6.2.2",
    "typescript": "^3.8.3",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  },
  "scripts": {
    "start": "webpack-dev-server  --mode development --open  --content-base public/"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bootstrap": "^4.4.1",
    "sveltestrap": "^3.3.3"
  }
}
```

and webpack.config
```
const ForkTsCheckerWebpackPlugin = require("fork-ts-checker-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const path = require("path");

const mode = process.env.NODE_ENV || "development";
const prod = mode === "production";

module.exports = {
  entry: path.resolve(__dirname, "src/main.ts"),
  output: {
    path: path.resolve(__dirname, "public"),
    filename: "bundle.js"
  },
  devServer: {
    port: 5000
  },
  resolve: {
    alias: {
      svelte: path.resolve("node_modules", "svelte")
    },
    extensions: [".mjs", ".js", ".svelte", ".ts", ".tsx"],
    mainFields: ["svelte", "browser", "module", "main"]
  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: "ts-loader",
            options: {
              transpileOnly: true
            }
          }
        ]
      },
      {
        test: /\.tsx$/,
        use: [
          {
            loader: "svelte-loader",
            options: {
              emitCss: true,
              hotReload: true
            }
          },
          {
            loader: "svelte-draft-loader"
          }
        ]
      },
      {
        test: /\.svelte$/,
        use: [
          {
            loader: "svelte-loader",
            options: {
              emitCss: true,
              hotReload: true
            }
          }
        ]
      },
      {
        test: /\.scss$/,
        use: [
          prod ? MiniCssExtractPlugin.loader : "style-loader",
          "css-loader",
          "sass-loader"
        ]
      },
      {
        test: /\.css$/,
        use: [prod ? MiniCssExtractPlugin.loader : "style-loader", "css-loader"]
      }
    ]
  },

  plugins: [
    new ForkTsCheckerWebpackPlugin(),
    new MiniCssExtractPlugin({
      filename: "bundle.css"
    })
  ],

  mode
};
```

Thanks

**Comment by mistlog** [comment]
> Its possible use svelte-draft and typescript with no default exports?

No, a default export must be specified because "the default export is the component itself", which is the convention of svelte, see https://svelte.dev/docs#script_context_module.

**Comment by martinsura** [comment]
Ah ok, thanks for the asnwer.
